import {beforeAll,afterAll,describe,it,expect,vi} from 'vitest';
import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import type {VercelRequest,VercelResponse} from '@vercel/node';
import {defaultSubjects,defaultActivities} from './defaults';
import {signToken,COOKIE} from '../../api/_lib/auth';
const holder=vi.hoisted(()=>({db:null as unknown as PGlite}));
vi.mock('@neondatabase/serverless',()=>({neon:()=>{
 const sql=(strings:TemplateStringsArray,...params:unknown[])=>{const text=strings.reduce((a,s,i)=>a+(i?`$${i}`:'')+s,'');return {text,params,then:(resolve:(value:unknown)=>void,reject:(reason:unknown)=>void)=>holder.db.query(text,params).then(r=>JSON.parse(JSON.stringify(r.rows))).then(resolve,reject)};};
 sql.transaction=async(queries:{text:string;params:unknown[]}[])=>holder.db.transaction(async tx=>{const result=[];for(const q of queries)result.push(JSON.parse(JSON.stringify((await tx.query(q.text,q.params)).rows)));return result;});return sql;
}}));
import handler from '../../api/[...route]';
const secret='integration-test-secret-longer-than-thirty-two-characters';
async function request(path:string,method='GET',body?:unknown,auth=true){let status=200;let result:unknown;const headers:Record<string,string>={};const req={url:`/api/${path}`,method,body,cookies:auth?{[COOKIE]:signToken(secret)}:{},headers:{host:'localhost'},query:{}} as unknown as VercelRequest;const res={setHeader:(k:string,v:string)=>{headers[k]=v;},status:(s:number)=>{status=s;return res;},json:(data:unknown)=>{result=data;return res;}} as unknown as VercelResponse;await handler(req,res);return {status,body:result as Record<string,unknown>,headers};}
beforeAll(async()=>{vi.stubEnv('DATABASE_URL','postgresql://test');vi.stubEnv('AUTH_SECRET',secret);vi.stubEnv('APP_PASSCODE','private-test-passcode');holder.db=new PGlite();await holder.db.exec(await readFile(new URL('../../db/schema.sql',import.meta.url),'utf8'));for(const s of defaultSubjects)await holder.db.query('INSERT INTO subjects(id,name,color) VALUES($1,$2,$3)',[s.id,s.name,s.color]);for(const a of defaultActivities)await holder.db.query('INSERT INTO activity_types(id,name) VALUES($1,$2)',[a.id,a.name]);await holder.db.exec('INSERT INTO settings(singleton) VALUES(true)');},30000);
afterAll(async()=>{await holder.db.close();vi.unstubAllEnvs();});
describe('API with a PostgreSQL engine',()=>{
 it('rejects unauthenticated reads and writes',async()=>{expect((await request('state','GET',undefined,false)).status).toBe(401);expect((await request('sessions','POST',{},false)).status).toBe(401);});
 it('signs in with a protected cookie and exports valid data',async()=>{const login=await request('login','POST',{passcode:'private-test-passcode'},false);expect(login.status).toBe(200);expect(login.headers['Set-Cookie']).toContain('HttpOnly; Secure');expect((await request('export')).body.version).toBe(1);});
 it('persists one timer, supports pause/resume and saves exactly once',async()=>{expect((await request('timer','POST',{action:'start',subject_id:defaultSubjects[0].id,activity_type_id:defaultActivities[0].id})).status).toBe(200);expect((await request('timer','POST',{action:'start',subject_id:defaultSubjects[0].id,activity_type_id:defaultActivities[0].id})).status).toBe(409);const timer=(await request('timer')).body;expect((await request('timer','POST',{action:'pause',id:timer.id})).status).toBe(200);expect((await request('timer','POST',{action:'resume',id:timer.id})).status).toBe(200);const session={id:crypto.randomUUID(),subject_id:defaultSubjects[0].id,activity_type_id:defaultActivities[0].id,started_at:new Date().toISOString(),duration_minutes:35};const stop={action:'stop',id:timer.id,session};expect((await request('timer','POST',stop)).status).toBe(200);expect((await request('timer','POST',stop)).status).toBe(409);expect((await request('export')).body.sessions).toHaveLength(1);});
 it('validates requests, edits and deletes sessions',async()=>{expect((await request('sessions','POST',{duration_minutes:-5})).status).toBe(400);const state=(await request('export')).body;const session=(state.sessions as Record<string,unknown>[])[0];expect((await request('sessions','PUT',{...session,notes:'Revised notes'})).status).toBe(200);expect(((await request('export')).body.sessions as Record<string,unknown>[])[0].notes).toBe('Revised notes');expect((await request('sessions','DELETE',{id:session.id})).status).toBe(200);});
 it('loads and removes only sample data and validates imports before replacing',async()=>{expect((await request('data','POST',{action:'sample'})).status).toBe(200);const backup=(await request('export')).body;expect(backup.sessions).toHaveLength(45);expect((await request('import','POST',{...backup,subjects:[]})).status).toBe(400);expect((await request('export')).body.sessions).toHaveLength(45);expect((await request('import','POST',backup)).status).toBe(200);expect((await request('data','POST',{action:'remove-sample'})).status).toBe(200);expect((await request('export')).body.sessions).toHaveLength(0);});
 it('requires the exact reset phrase and restores defaults',async()=>{expect((await request('data','POST',{action:'reset'})).status).toBe(400);expect((await request('data','POST',{action:'reset',confirmation:'RESET ALL DATA'})).status).toBe(200);expect((await request('state')).body.subjects).toHaveLength(6);});
 it('throttles logins using durable database counters',async()=>{await holder.db.query("INSERT INTO login_attempts(bucket,attempts,reset_at) VALUES('irrelevant',1,now())");for(let i=0;i<10;i++)await request('login','POST',{passcode:'incorrect'},false);expect((await request('login','POST',{passcode:'private-test-passcode'},false)).status).toBe(429);},15000);
});

