import {useState} from 'react';
import {Link} from 'react-router-dom';
import {format,startOfWeek,startOfMonth,startOfDay,endOfDay,subDays} from 'date-fns';
import {Flame,Target,Clock3,CalendarDays} from 'lucide-react';
import {useData} from '../hooks/useData';
import {minutes,hours,periods,streaks,between,breakdown} from '../lib/stats';
import {DailyChart,Donut} from '../components/Charts';
import {SessionList} from '../components/SessionList';
export default function Dashboard(){const data=useData();const [days,setDays]=useState(7),[period,setPeriod]=useState<'today'|'week'|'month'>('week');const [from,setFrom]=useState(format(subDays(new Date(),29),'yyyy-MM-dd')),[to,setTo]=useState(format(new Date(),'yyyy-MM-dd'));const totals=periods(data.sessions),streak=streaks(data.sessions);const range=from&&to&&from<=to?between(data.sessions,startOfDay(new Date(from+'T00:00:00')),endOfDay(new Date(to+'T00:00:00'))):[];const selected=between(data.sessions,period==='today'?startOfDay(new Date()):period==='week'?startOfWeek(new Date(),{weekStartsOn:1}):startOfMonth(new Date()),new Date());const subjectTotals=breakdown(selected,'subject_id');const weeklyTotals=breakdown(between(data.sessions,startOfWeek(new Date(),{weekStartsOn:1}),new Date()),'subject_id');const goal=data.settings.weekly_goal_minutes;
 return <><div className="page-heading"><div><div className="eyebrow">{format(new Date(),'EEEE, MMMM d')}</div><h1>Your effort, at a glance</h1><p>A clear view of the work you’re putting in.</p></div><div className="streak-pill"><Flame size={18}/>{streak.current}-day streak</div></div><div className="stat-grid">{[{title:'Today',value:hours(totals.today),sub:'A little progress counts',icon:Clock3},{title:'This week',value:hours(totals.week),sub:'Monday to Sunday',icon:CalendarDays},{title:'This month',value:hours(totals.month),sub:format(new Date(),'MMMM yyyy'),icon:BookIcon},{title:'Longest streak',value:`${streak.longest} days`,sub:`${streak.current} days and counting`,icon:Flame}].map(({title,value,sub,icon:Icon})=><section className="stat-card" key={title}><div><span>{title}</span><Icon size={18}/></div><strong>{value}</strong><small>{sub}</small></section>)}</div>
 <div className="dashboard-main"><section className="card"><div className="card-heading"><div><h2>Study rhythm</h2><p>Your daily hours, by subject</p></div><div className="segmented">{[7,30].map(n=><button className={days===n?'active':''} key={n} onClick={()=>setDays(n)}>{n} days</button>)}</div></div><DailyChart sessions={data.sessions} subjects={data.subjects} days={days}/><div className="inline-legend">{data.subjects.filter(s=>!s.archived).map(s=><span key={s.id}><i style={{background:s.color}}/>{s.name.replace('Language & Literature','Lang & Lit')}</span>)}</div></section><section className="card goal-card"><div className="card-heading"><h2>This week’s goal</h2><Target size={20}/></div><div className="goal-ring" style={{background:`conic-gradient(var(--accent) ${goal?Math.min(100,totals.week/goal*100):0}%,var(--soft) 0)`}}><div><strong>{goal?Math.round(totals.week/goal*100):0}<small>%</small></strong><span>of weekly goal</span></div></div><p><strong>{hours(totals.week)}</strong> <span className="muted">/ {hours(goal)}</span></p><span className="muted">{!goal?'Set a goal to find your rhythm':totals.week>=goal?'You reached your weekly goal!':`${hours(goal-totals.week)} to go. You’ve got this.`}</span><Link className="text-link" to="/settings">Adjust weekly goal</Link></section></div>
 <section className="card"><div className="card-heading"><div><h2>Every subject matters</h2><p>Find your balance across the diploma</p></div><label className="compact-label"><span className="sr-only">Breakdown period</span><select value={period} onChange={e=>setPeriod(e.target.value as typeof period)}><option value="today">Today</option><option value="week">This week</option><option value="month">This month</option></select></label></div><div className="subject-grid">{data.subjects.filter(s=>!s.archived).map(s=><Link className="subject-card" key={s.id} to={`/subjects/${s.id}`}><div><span className="color-dot" style={{background:s.color}}/><h3>{s.name}</h3></div><strong>{hours(subjectTotals[s.id]||0)}</strong><div className="progress-track"><span style={{width:`${Math.min(100,(subjectTotals[s.id]||0)/Math.max(1,minutes(selected))*100)}%`,background:s.color}}/></div><small>{s.weekly_goal_minutes?`${hours(weeklyTotals[s.id]||0)} / ${hours(s.weekly_goal_minutes)} weekly goal`:`${selected.filter(x=>x.subject_id===s.id).length} sessions`}</small></Link>)}</div></section>
 <div className="section-heading"><h2>Where your time goes</h2><div className="date-filters"><label>From<input aria-label="Chart start date" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input aria-label="Chart end date" type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/></label></div></div>{from>to&&<p role="alert" className="error">Choose an end date after the start date.</p>}<div className="two-columns"><section className="card"><h2>By subject</h2><Donut sessions={range} items={data.subjects} by="subject_id"/></section><section className="card"><h2>By activity</h2><Donut sessions={range} items={data.activity_types} by="activity_type_id"/></section></div><section className="card"><div className="card-heading"><h2>Recent sessions</h2><Link className="text-link" to="/log">View study log</Link></div><SessionList sessions={[...data.sessions].sort((a,b)=>b.started_at.localeCompare(a.started_at)).slice(0,5)}/></section></>;
}
const BookIcon=Clock3;
