import {useState} from 'react';
import {Plus,Download,Upload,Pencil} from 'lucide-react';
import {useData,useSave} from '../hooks/useData';
import {api,download,csvCell} from '../lib/api';
import {exportSchema} from '../lib/schemas';
import {Modal} from '../components/Modal';
import type {Subject,Activity,Backup} from '../types';
export default function Settings(){const data=useData(),save=useSave();const [edit,setEdit]=useState<{kind:'subject'|'activity';item:Subject|Activity}>(),[backup,setBackup]=useState<Backup>(),[confirm,setConfirm]=useState<'sample'|'remove-sample'|'reset'>(),[step,setStep]=useState(1),[phrase,setPhrase]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const perform=async(path:string,body:unknown,method='POST')=>{setError('');setMessage('');try{await save.mutateAsync({path,body,method});setMessage('Changes saved.');return true;}catch(e){setError((e as Error).message);return false;}};
 async function exportData(csv=false){setBusy(true);setError('');try{const b=await api<Backup>('export');if(csv){const rows=[['id','subject','activity','started_at','duration_minutes','notes','tags','focus_rating'],...b.sessions.map(s=>[s.id,b.subjects.find(x=>x.id===s.subject_id)?.name,b.activity_types.find(x=>x.id===s.activity_type_id)?.name,s.started_at,s.duration_minutes,s.notes,s.tags.join('; '),s.focus_rating])];download(rows.map(r=>r.map(csvCell).join(',')).join('\r\n'),'studyline-sessions.csv','text/csv;charset=utf-8');}else download(JSON.stringify(b,null,2),'studyline-backup.json','application/json');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><div className="page-heading"><div><div className="eyebrow">MAKE IT YOURS</div><h1>Settings</h1><p>Your subjects, your goals, your study space.</p></div></div>{message&&<p className="success" role="status">{message}</p>}{error&&<p className="error-banner" role="alert">{error} Please try the action again.</p>}<div className="two-columns"><section className="card"><h2>Weekly goal & preferences</h2><form key={JSON.stringify(data.settings)} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void perform('settings',{weekly_goal_minutes:Math.round(Number(f.get('goal'))*60),theme:f.get('theme'),time_format:f.get('time')},'PUT');}}><label>Total weekly goal (hours)<input name="goal" type="number" min="0" max="168" step="0.25" defaultValue={data.settings.weekly_goal_minutes/60} required/></label><div className="form-grid"><label>Theme<select name="theme" defaultValue={data.settings.theme}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label>Time format<select name="time" defaultValue={data.settings.time_format}><option value="24h">24-hour</option><option value="12h">12-hour</option></select></label></div><button className="primary" disabled={save.isPending}>Save preferences</button></form></section><section className="card"><h2>Your data, with you</h2><p className="muted">Download a full backup or take your session history to a spreadsheet.</p><div className="data-actions"><button className="secondary" disabled={busy} onClick={()=>exportData()}><Download size={16}/> Export all data (JSON)</button><button className="secondary" disabled={busy} onClick={()=>exportData(true)}><Download size={16}/> Export sessions (CSV)</button><label className="import-label"><Upload size={16}/> Import a JSON backup<input type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setError('');try{if(file.size>3_500_000)throw new Error('Backup exceeds the 3.5 MB import limit.');const parsed=exportSchema.parse(JSON.parse(await file.text()));setBackup(parsed);}catch(e){setError((e as Error).message);}}}/></label></div><small className="muted">Imports replace your data after you review and confirm. The active timer is not included in backups.</small></section></div>
 <section className="card"><div className="card-heading"><div><h2>Subjects</h2><p>Archive a subject to keep its history without showing it in the timer.</p></div><button className="secondary" onClick={()=>setEdit({kind:'subject',item:{id:crypto.randomUUID(),name:'',color:'#5366d9',archived:false,sort_order:data.subjects.length,weekly_goal_minutes:0}})}><Plus size={16}/> Add subject</button></div><div className="settings-list">{data.subjects.map(s=><div key={s.id}><span className="color-dot" style={{background:s.color}}/><strong>{s.name}</strong><span className="muted">{s.archived?'Archived':s.weekly_goal_minutes?`${s.weekly_goal_minutes/60}h / week`:'No subject goal'}</span><button className="icon-button" aria-label={`Edit ${s.name}`} onClick={()=>setEdit({kind:'subject',item:s})}><Pencil size={17}/></button></div>)}</div></section>
 <section className="card"><div className="card-heading"><h2>Activity types</h2><button className="secondary" onClick={()=>setEdit({kind:'activity',item:{id:crypto.randomUUID(),name:'',archived:false,sort_order:data.activity_types.length}})}><Plus size={16}/> Add activity</button></div><div className="activity-grid">{data.activity_types.map(a=><button className="activity-edit" key={a.id} onClick={()=>setEdit({kind:'activity',item:a})}><span>{a.name}{a.archived?' · archived':''}</span><Pencil size={15}/></button>)}</div></section>
 <section className="card danger-zone"><h2>Sample data & reset</h2><p className="muted">Explore the charts with sample sessions. Remove them any time without touching your own sessions.</p><div className="data-buttons"><button className="secondary" onClick={()=>{setConfirm('sample');setStep(1);}}>Load sample data</button><button className="secondary" onClick={()=>{setConfirm('remove-sample');setStep(1);}}>Remove sample data</button><button className="danger-outline" onClick={()=>{setConfirm('reset');setStep(1);setPhrase('');}}>Reset all data</button></div></section>
 {edit&&<Modal title={`${edit.item.name?'Edit':'Add'} ${edit.kind}`} onClose={()=>setEdit(undefined)}><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const item={...edit.item,name:String(f.get('name')),archived:f.get('archived')==='on',...(edit.kind==='subject'?{color:String(f.get('color')),weekly_goal_minutes:Math.round(Number(f.get('goal'))*60)}:{})};if(await perform(edit.kind==='subject'?'subjects':'activity-types',item,'PUT'))setEdit(undefined);}}><label>Name<input name="name" defaultValue={edit.item.name} maxLength={100} required autoFocus/></label>{edit.kind==='subject'&&<div className="form-grid"><label>Color<input name="color" type="color" defaultValue={(edit.item as Subject).color}/></label><label>Weekly goal (hours)<input name="goal" type="number" step="0.25" min="0" max="168" defaultValue={(edit.item as Subject).weekly_goal_minutes/60}/></label></div>}<label className="checkbox-label"><input name="archived" type="checkbox" defaultChecked={edit.item.archived}/>Archived</label>{error&&<p className="error" role="alert">{error}</p>}<div className="dialog-actions"><button type="button" className="secondary" onClick={()=>setEdit(undefined)}>Cancel</button><button className="primary" disabled={save.isPending}>Save {edit.kind}</button></div></form></Modal>}
 {backup&&<Modal title="Review your import" onClose={()=>setBackup(undefined)}><p>This backup contains <strong>{backup.sessions.length} sessions</strong>, {backup.subjects.length} subjects, and {backup.activity_types.length} activities.</p><p>It will replace your current {data.sessions.length} sessions and all settings, and clear the active timer. Export a backup first if you want to keep them.</p>{error&&<p className="error" role="alert">{error}</p>}<div className="dialog-actions"><button className="secondary" onClick={()=>setBackup(undefined)}>Cancel</button><button className="danger" disabled={save.isPending} onClick={async()=>{if(await perform('import',backup))setBackup(undefined);}}>Replace with this backup</button></div></Modal>}
 {confirm&&<Modal title={step===1?'Review this change':'Confirm your choice'} onClose={()=>setConfirm(undefined)}><p>{confirm==='sample'?'Add 45 example sessions to your history? Existing sample sessions will be replaced. Your own sessions will stay.':confirm==='remove-sample'?'Remove all sample sessions? Your own sessions will stay.':'Delete every session, clear your timer, and restore the default subjects, activities, and settings? This cannot be undone without a backup.'}</p>{step===2&&confirm==='reset'&&<label>Type RESET ALL DATA<input value={phrase} onChange={e=>setPhrase(e.target.value)} autoFocus/></label>}{error&&<p className="error" role="alert">{error}</p>}<div className="dialog-actions"><button className="secondary" onClick={()=>setConfirm(undefined)}>Cancel</button><button className={confirm==='reset'?'danger':'primary'} disabled={save.isPending||(step===2&&confirm==='reset'&&phrase!=='RESET ALL DATA')} onClick={async()=>{if(step===1){setStep(2);return;}if(await perform('data',{action:confirm,...(confirm==='reset'?{confirmation:phrase}:{})}))setConfirm(undefined);}}>{step===1?'Continue':confirm==='reset'?'Reset all data':'Confirm change'}</button></div></Modal>}</>;
}
