import {useState} from 'react';
import {format} from 'date-fns';
import {useData,useSave} from '../hooks/useData';
import type {Session} from '../types';
import {Modal} from './Modal';
export function SessionForm({session,timerId,onClose}:{session?:Session;timerId?:string;onClose:()=>void}){
 const data=useData(),save=useSave();const [error,setError]=useState('');
 const activeSubjects=data.subjects.filter(s=>!s.archived||s.id===session?.subject_id),activities=data.activity_types.filter(a=>!a.archived||a.id===session?.activity_type_id);
 return <Modal title={timerId?'Finish your session':session?'Edit session':'Log study time'} onClose={onClose}><form onSubmit={async e=>{e.preventDefault();setError('');const f=new FormData(e.currentTarget);const entry:Session={id:session?.id||crypto.randomUUID(),subject_id:String(f.get('subject')),activity_type_id:String(f.get('activity')),started_at:new Date(String(f.get('started'))).toISOString(),duration_minutes:Number(f.get('duration')),notes:String(f.get('notes')),tags:String(f.get('tags')).split(',').map(s=>s.trim()).filter(Boolean),focus_rating:f.get('focus')?Number(f.get('focus')):null,is_sample:session?.is_sample||false};try{await save.mutateAsync(timerId?{path:'timer',body:{action:'stop',id:timerId,session:entry}}:{path:'sessions',method:session?'PUT':'POST',body:entry});onClose();}catch(e){setError((e as Error).message);}}}>
 <div className="form-grid"><label>Subject<select name="subject" defaultValue={session?.subject_id||activeSubjects[0]?.id} required>{activeSubjects.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Activity<select name="activity" defaultValue={session?.activity_type_id||activities[0]?.id} required>{activities.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label><label>Date & start time<input name="started" type="datetime-local" defaultValue={format(new Date(session?.started_at||Date.now()),"yyyy-MM-dd'T'HH:mm")} required/></label><label>Duration (minutes)<input name="duration" type="number" min="0.1" max="1440" step="0.1" defaultValue={session?.duration_minutes||30} required/></label></div>
 <label>Notes<textarea name="notes" maxLength={10000} defaultValue={session?.notes} placeholder="What did you work on?" rows={3}/></label><label>Tags <span className="muted">· separated by commas</span><input name="tags" defaultValue={session?.tags.join(', ')} placeholder="e.g. calculus, chapter 4"/></label><label>Focus rating<select name="focus" defaultValue={session?.focus_rating||''}><option value="">Not rated</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} / 5{n===5?' · Fully focused':n===1?' · Easily distracted':''}</option>)}</select></label>
 {error&&<p className="error" role="alert">{error} Submit again to retry.</p>}<div className="dialog-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={save.isPending||!activeSubjects.length||!activities.length}>{save.isPending?'Saving…':'Save session'}</button></div></form></Modal>;
}
