import {useState} from 'react';
import {format} from 'date-fns';
import {Pencil,Trash2} from 'lucide-react';
import {useData,useSave} from '../hooks/useData';
import {hours} from '../lib/stats';
import {SessionForm} from './SessionForm';
import {Modal} from './Modal';
import type {Session} from '../types';
export function SessionList({sessions}:{sessions:Session[]}){const data=useData(),save=useSave();const [edit,setEdit]=useState<Session>(),[remove,setRemove]=useState<Session>();return <>{sessions.length?<div className="table-scroll"><table><thead><tr><th>Subject / activity</th><th>When</th><th>Duration</th><th>Notes & tags</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{sessions.map(s=>{const subject=data.subjects.find(x=>x.id===s.subject_id);return <tr key={s.id}><td><div className="session-subject"><span className="color-dot" style={{background:subject?.color}}/><strong>{subject?.name||'Unknown subject'}</strong></div><span className="secondary-text">{data.activity_types.find(a=>a.id===s.activity_type_id)?.name}</span></td><td className="nowrap">{format(new Date(s.started_at),'MMM d, yyyy')}<span className="secondary-text">{format(new Date(s.started_at),data.settings.time_format==='24h'?'HH:mm':'h:mm a')}</span></td><td className="nowrap"><strong>{hours(s.duration_minutes)}</strong>{s.focus_rating&&<span className="secondary-text">Focus {s.focus_rating}/5</span>}</td><td className="notes-cell">{s.notes||<span className="muted">—</span>}<div className="tags">{s.tags.map((t,i)=><span key={i}>{t}</span>)}{s.is_sample&&<span>Sample</span>}</div></td><td><div className="row-actions"><button className="icon-button" aria-label={`Edit ${subject?.name} session`} onClick={()=>setEdit(s)}><Pencil size={16}/></button><button className="icon-button" aria-label={`Delete ${subject?.name} session`} onClick={()=>setRemove(s)}><Trash2 size={16}/></button></div></td></tr>;})}</tbody></table></div>:<div className="empty"><strong>No sessions here yet</strong><p>Log some study time, or adjust your filters.</p></div>}{edit&&<SessionForm session={edit} onClose={()=>setEdit(undefined)}/>} {remove&&<Modal title="Delete this session?" onClose={()=>setRemove(undefined)}><p>This will remove {hours(remove.duration_minutes)} from your study history.</p>{save.error&&<p role="alert" className="error">{save.error.message}</p>}<div className="dialog-actions"><button className="secondary" onClick={()=>setRemove(undefined)}>Keep session</button><button className="danger" disabled={save.isPending} onClick={()=>save.mutate({path:'sessions',method:'DELETE',body:{id:remove.id}},{onSuccess:()=>setRemove(undefined)})}>Delete session</button></div></Modal>}</>;}
