import {useState,useEffect} from 'react';
import {Play,Pause,Square,Timer as TimerIcon} from 'lucide-react';
import {useData,useSave} from '../hooks/useData';
import {elapsed} from '../lib/stats';
import {SessionForm} from './SessionForm';
import type {Session} from '../types';
export function Timer(){const data=useData(),save=useSave(),timer=data.timer;const [subject,setSubject]=useState(''),[activity,setActivity]=useState(''),[now,setNow]=useState(Date.now()),[finish,setFinish]=useState<Session|null>(null);
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id);},[]);
 const subjects=data.subjects.filter(s=>!s.archived),activities=data.activity_types.filter(a=>!a.archived);const seconds=Math.floor(timer?elapsed(timer,now)/1000:0);const clock=[Math.floor(seconds/3600),Math.floor(seconds/60)%60,seconds%60].map(n=>String(n).padStart(2,'0')).join(':');
 return <section className="timer-card" aria-label="Study timer"><div className="timer-label"><TimerIcon size={20}/><div><strong>Focus timer</strong><span>{timer?(timer.paused_at?'Paused · take a breath':'One session at a time'):'Make a little progress today'}</span></div></div><div className="timer-selects"><label className="sr-only" htmlFor="timer-subject">Timer subject</label><select id="timer-subject" disabled={!!timer} value={timer?.subject_id||subject||subjects[0]?.id||''} onChange={e=>setSubject(e.target.value)}>{(timer?data.subjects:subjects).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><label className="sr-only" htmlFor="timer-activity">Timer activity</label><select id="timer-activity" disabled={!!timer} value={timer?.activity_type_id||activity||activities[0]?.id||''} onChange={e=>setActivity(e.target.value)}>{(timer?data.activity_types:activities).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div><div className="timer-clock" aria-label={`Elapsed ${clock}`}>{clock}</div><div className="timer-actions">{timer?<><button className="timer-button" disabled={save.isPending} onClick={()=>save.mutate({path:'timer',body:{action:timer.paused_at?'resume':'pause',id:timer.id}})}>{timer.paused_at?<Play size={17}/>:<Pause size={17}/>} {timer.paused_at?'Resume':'Pause'}</button><button className="timer-stop" aria-label="Stop and review session" disabled={save.isPending} onClick={async()=>{try{if(!timer.paused_at)await save.mutateAsync({path:'timer',body:{action:'pause',id:timer.id}});setFinish({id:crypto.randomUUID(),subject_id:timer.subject_id,activity_type_id:timer.activity_type_id,started_at:timer.started_at,duration_minutes:Math.min(1440,Math.max(0.1,Math.round(elapsed(timer)/6000)/10)),notes:'',tags:[],focus_rating:null,is_sample:false});}catch{/* Error is displayed below. */}}}><Square size={16}/></button></>:<button className="timer-button" disabled={save.isPending||!subjects.length||!activities.length} onClick={()=>save.mutate({path:'timer',body:{action:'start',subject_id:subject||subjects[0]?.id,activity_type_id:activity||activities[0]?.id}})}><Play size={17}/> Start focus</button>}</div>{save.error&&<p className="timer-error" role="alert">{save.error.message} <button onClick={()=>save.variables&&save.mutate(save.variables)}>Retry</button></p>}{finish&&timer&&<SessionForm session={finish} timerId={timer.id} onClose={()=>setFinish(null)}/>}</section>;
}
