import React,{lazy,Suspense,useEffect,useState} from 'react';
import ReactDOM from 'react-dom/client';
import {BrowserRouter,Routes,Route,NavLink,Link,useNavigate} from 'react-router-dom';
import {QueryClient,QueryClientProvider,useQuery} from '@tanstack/react-query';
import {LayoutDashboard,BookOpen,History,Settings as SettingsIcon,LogOut,Plus,BarChart3,LockKeyhole} from 'lucide-react';
import {api,ApiError} from './lib/api';
import {DataContext} from './hooks/useData';
import {SessionForm} from './components/SessionForm';
import {Timer} from './components/Timer';
import type {State} from './types';
import './style.css';
const Dashboard=lazy(()=>import('./pages/Dashboard')),HistoryPage=lazy(()=>import('./pages/History')),SubjectPage=lazy(()=>import('./pages/Subject')),SettingsPage=lazy(()=>import('./pages/Settings'));
const client=new QueryClient({defaultOptions:{queries:{retry:(n,error)=>!(error instanceof ApiError&&[401,403,503].includes(error.status))&&n<2,refetchOnWindowFocus:true}}});
function App(){const [signedOut,setSignedOut]=useState(false),[logging,setLogging]=useState(false),[logoutError,setLogoutError]=useState('');const navigate=useNavigate();const query=useQuery<State>({queryKey:['state'],queryFn:()=>api('state'),enabled:!signedOut,refetchInterval:10000});
 useEffect(()=>{const expired=()=>{setSignedOut(true);client.removeQueries({queryKey:['state']});};window.addEventListener('auth-expired',expired);return()=>window.removeEventListener('auth-expired',expired);},[]);
 const theme=query.data?.settings.theme||'system';useEffect(()=>{const media=matchMedia('(prefers-color-scheme: dark)');const apply=()=>document.documentElement.dataset.theme=theme==='system'?(media.matches?'dark':'light'):theme;apply();media.addEventListener('change',apply);return()=>media.removeEventListener('change',apply);},[theme]);
 if(signedOut||(query.error instanceof ApiError&&query.error.status===401))return <Login onLogin={()=>{setSignedOut(false);client.invalidateQueries({queryKey:['state']});navigate('/');}}/>;
 if(query.isLoading)return <div className="full-state"><BarChart3 size={32}/><h1>Opening your study space…</h1></div>;
 if(!query.data)return <div className="full-state"><h1>Let’s get connected</h1><p role="alert">{query.error?.message||'Unable to load data'}</p><button className="primary" onClick={()=>query.refetch()}>Retry connection</button></div>;
 const data=query.data;return <DataContext.Provider value={data}><a className="skip" href="#main">Skip to content</a><aside className="sidebar"><Link className="brand" to="/"><span className="brand-mark"><BarChart3 size={25}/></span>studyline<span className="brand-dot">.</span></Link><div className="workspace-label">YOUR STUDY SPACE</div><nav className="main-nav"><NavLink to="/" end><LayoutDashboard size={19}/>Overview</NavLink><NavLink to="/log"><History size={19}/>Study log</NavLink><NavLink to="/settings"><SettingsIcon size={19}/>Settings</NavLink></nav><div className="workspace-label subjects-label">IB SUBJECTS</div><nav className="subject-nav">{data.subjects.filter(s=>!s.archived).map(s=><NavLink key={s.id} to={`/subjects/${s.id}`}><span className="color-dot" style={{background:s.color}}/>{s.name}</NavLink>)}</nav><div className="sidebar-bottom"><div className="student-avatar"><BookOpen size={19}/></div><div><strong>My IB journey</strong><span>Personal workspace</span></div><button className="icon-button" aria-label="Log out" onClick={async()=>{try{await api('logout','POST',{});setSignedOut(true);client.clear();}catch(e){setLogoutError((e as Error).message);}}}><LogOut size={18}/></button></div></aside><div className="workspace"><header className="topbar"><span className="topbar-label">IB DIPLOMA PROGRAMME</span><span className="sync-status">{query.isFetching?'Syncing…':'Saved across your devices'}</span><button className="primary" onClick={()=>setLogging(true)}><Plus size={17}/> Log session</button></header><main id="main">{(query.isError||logoutError)&&<div role="alert" className="error-banner">{logoutError||query.error?.message}<button onClick={()=>{setLogoutError('');query.refetch();}}>Retry</button></div>}<Timer/><Suspense fallback={<p className="empty">Loading page…</p>}><Routes><Route path="/" element={<Dashboard/>}/><Route path="/log" element={<HistoryPage/>}/><Route path="/subjects/:id" element={<SubjectPage/>}/><Route path="/settings" element={<SettingsPage/>}/><Route path="*" element={<div className="empty"><h1>That page took a study break.</h1><Link to="/">Back to overview</Link></div>}/></Routes></Suspense></main><footer>Small steps. Steady progress.</footer></div>{logging&&<SessionForm onClose={()=>setLogging(false)}/>}</DataContext.Provider>;
}
function Login({onLogin}:{onLogin:()=>void}){const [error,setError]=useState(''),[busy,setBusy]=useState(false);return <div className="login"><div className="login-story"><span className="brand"><span className="brand-mark"><BarChart3/></span>studyline.</span><div><span className="eyebrow">YOUR IB JOURNEY, IN FOCUS</span><h1>A little more<br/>progress.<br/><em>Every day.</em></h1><p>A place for your effort to add up.</p></div><span>Six subjects. One personal study space.</span></div><div className="login-form"><div className="lock-icon"><LockKeyhole/></div><h2>Welcome back</h2><p className="muted">Enter your passcode to open your study space.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('login','POST',{passcode:String(new FormData(e.currentTarget).get('passcode'))});onLogin();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>Passcode<input name="passcode" type="password" autoComplete="current-password" autoFocus required maxLength={1024}/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Signing in…':'Open my study space'}</button></form><p className="login-note">Your study history stays private.</p></div></div>;}
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={client}><BrowserRouter><App/></BrowserRouter></QueryClientProvider></React.StrictMode>);
